NAME = libft.a

SRCS = $(addsuffix .c, ft_atoi ft_atol ft_bzero ft_calloc ft_isalnum ft_isalpha ft_isascii ft_isdigit ft_isprint ft_itoa ft_memchr ft_memcmp ft_memcpy ft_memmove ft_memset ft_putchar_fd ft_putendl_fd ft_putnbr_fd ft_putstr_fd ft_split ft_strchr ft_strcmp ft_strdup ft_striteri ft_strjoin ft_strjoin_multi ft_strlcat ft_strlcpy ft_strlen ft_strmapi ft_strncmp ft_strndup ft_strnstr ft_strrchr ft_strtrim ft_substr ft_tolower ft_toupper)

BONUS = $(addsuffix .c, ft_lstadd_back ft_lstadd_front ft_lstclear ft_lstdelone ft_lstiter ft_lstlast ft_lstmap ft_lstnew ft_lstsize)

PRINTF = $(addsuffix .c, ft_helper ft_printf put_char put_hex put_int put_string put_unsigned_int)

GNL = $(addsuffix .c, get_next_line_bonus get_next_line_utils_bonus get_line_len)

STRARR = $(addsuffix .c, ft_lst_to_strarr free_strarr ft_strarrcpy \
		 ft_strarrlen print_strarr)

OBJS = ${SRCS:.c=.o}
OBJS_BONUS = ${BONUS:.c=.o}
OBJS_PRINTF = ${PRINTF:.c=.o}
OBJS_GNL = ${GNL:.c=.o}
OBJS_STRARR = ${STRARR:.c=.o}

CC = gcc
RM = rm -f
CFLAGS = -Wall -Wextra -Werror -g3 -fsanitize=address

GREEN = \033[0;32m
BLUE  = \033[0;36m
RESET = \033[0m

.c.o:
	${CC} ${CFLAGS} -g -c $< -o ${<:.c=.o}

${NAME}: ${OBJS} ${OBJS_BONUS} ${OBJS_PRINTF} ${OBJS_GNL} ${OBJS_STRARR}
	ar rcs ${NAME} ${OBJS} ${OBJS_BONUS} ${OBJS_PRINTF} ${OBJS_GNL} \
		${OBJS_STRARR}

clean:
	${RM} ${OBJS} ${OBJS_BONUS} ${OBJS_PRINTF} ${OBJS_GNL} ${OBJS_STRARR}

all: ${NAME}


fclean: clean
	${RM} ${NAME}
	${RM} compile_commands.json

# |--- CompileDB (Magic Rule) -------------------|
compiledb:
	@if which compiledb > /dev/null; then \
		echo "$(BLUE)|--Generating libft JSONs-----------|$(RESET)"; \
		compiledb -n make -B; \
		echo "$(GREEN)|--Libft Database updated!----------|$(RESET)"; \
	else \
		echo "Error: compiledb not found. Run: pip3 install compiledb"; \
	fi

re: fclean all
